config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  resources 'jobs', only: [:index, :show, :destroy]
  post 'create_job', to: 'jobs#create'
  # post 'destroy_job/:id', to: 'jobs#destroy'

  resources 'events', only: [:index, :show, :create, :destroy]

  resources 'sessions', only: :create
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  get "/auth/:provider/callback" => "sessions#google_auth"

  resources 'home', only: :show

  get 'signup', to: 'registrations#new', as: 'new_registration'

  resources 'users', only: [:create, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_events
  has_many :events, through: :user_events
  has_many :user_jobs
  has_many :jobs, through: :user_jobs
  has_many :user_languages
  has_many :languages, through: :user_languages

  # validates :username, uniqueness: true
  # validates :username, presence: true
  # validates :password, presence: true
  # validates :password_confirmation, presence: true

  #include Gauth::GauthCreator

  has_secure_password

  def self.from_omniauth(auth)
    GauthCreator.service_from_omniauth(auth)
  end

  def add_omniauth_params(auth)
    update(provider_uid: auth.uid) unless provider_uid
    update(g_access_token: auth.credentials.token, g_refresh_token: auth.credentials.refresh_token) if provider_uid == auth.uid
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for joining TechMe, bro. Your account has be activated."
    else
      flash.now[:alert] = "There was an error with your registration. Please try again."
      render 'registrations/new'
    end
  end

  def show
    @job = Job.new
    @event = Event.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<%= render 'shared/errors' %>

<button class="btn btn-info btn-lg">
<%= link_to "Sync your Google Calendar", "/auth/google_oauth2" %>
</button>

<!-- <%= link_to "Sign in with Google", "/auth/google_oauth2" %> -->

<h1>New Event Search</h1>

<%= form_tag events_path, method: :get do %>
  <%= text_field_tag "location", nil, class: "form-control", id: "event_location", placeholder: "location", required: true %>

  <% cache do %>
  <% Language.all.each do |language| %>
    <%= check_box_tag 'language_selected[]', language.title, false, class: "iCheck-helper" %>
    <%= language.title %>
  <% end %>
  <% end %>

  <br><br>

  <%= submit_tag "New Event Search", class: "form_submit btn btn-primary btn-lg" %>
<% end %>

<h1>New Job Search</h1>

<%= form_tag jobs_path, method: :get do %>
  <%= text_field_tag "location", nil, class: "form-control", id: "job_location", placeholder: "location", required: true %>

  <% cache do %>
  <% Language.all.each do |language| %>
    <%= check_box_tag 'language_selected[]', language.id, false, class: "iCheck-helper" %>
    <%= language.title %>
  <% end %>
  <% end %>

  <br><br>

  <%= submit_tag "New Job Search", class: "form_submit btn btn-primary btn-lg" %>
<% end %>

<section class="page-block" id="features">

  <%= render 'layouts/tabs' %>

</section>