config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  resources 'jobs', only: [:index, :show, :destroy]
  post 'create_job', to: 'jobs#create'
  # post 'destroy_job/:id', to: 'jobs#destroy'

  resources 'events', only: [:index, :show, :create, :destroy]

  resources 'sessions', only: :create
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  get "/auth/:provider/callback" => "sessions#google_auth"

  resources 'home', only: :show

  get 'signup', to: 'registrations#new', as: 'new_registration'

  resources 'users', only: [:create, :show, :edit, :update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events
  belongs_to :language

  def self.get_events(location, languages)
    events = []
    languages.each do |language| 
      events << meetup_call(location, language)
    end
    events 
  end

  private

  def self.meetup_call(location, language)
    JSON.parse(RestClient.get("https://api.meetup.com/find/groups?key=#{ENV["meetup_app_key"]}&sign=true&photo-host=public&country=USA&upcoming_events=true&location=#{location}&text=#{language}&radius=5&category=34&page=20"))
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :user_jobs
  has_many :users, through: :user_jobs

  belongs_to :language
  # validates :title, uniqueness: true

  def self.get_jobs(location, time, languages)
    jobs = []

    languages.each do |language|
      jobs << format_sections(github_call(location, time, language))
    end
    jobs
  end

  def self.format_sections(json)
    json.each do |job|
      job["created_at"] = DateTime.parse(job["created_at"]).strftime("%A, %d %b %Y %l:%M %p")
    end
  end

  private

  def self.github_call(location, time, language)
    JSON.parse(RestClient.get("https://jobs.github.com/positions.json?description=#{language}&location=#{location}"))
  end

end

app/models/language.rb
class Language < ApplicationRecord
  has_many :events
  has_many :jobs
  has_many :user_languages
  has_many :users, through: :user_languages
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_events
  has_many :events, through: :user_events
  has_many :user_jobs
  has_many :jobs, through: :user_jobs
  has_many :user_languages
  has_many :languages, through: :user_languages

  # validates :username, uniqueness: true
  # validates :username, presence: true
  # validates :password, presence: true
  # validates :password_confirmation, presence: true

  #include Gauth::GauthCreator

  has_secure_password

  def self.from_omniauth(auth)
    GauthCreator.service_from_omniauth(auth)
  end

  def add_omniauth_params(auth)
    update(provider_uid: auth.uid) unless provider_uid
    update(g_access_token: auth.credentials.token, g_refresh_token: auth.credentials.refresh_token) if provider_uid == auth.uid
  end

end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # validates_uniqueness_of :user_id, :scope => :event_id
end

app/models/user_job.rb
class UserJob < ApplicationRecord
  belongs_to :user
  belongs_to :job

  # validates_uniqueness_of :user_id, :scope => :job_id
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = EventCreator.create_events(params)
    fresh_when etag: @jobs
  end

  def show
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      @current_user.events << @event
      render json: {
        success: true,
        eventID: params[:event_id]
      }
    else
      render json: {
        success: false,
        eventID: params[:event_id]
      }
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.users.length > 1
      UserEvent.find(params[:id]).destroy
      render json: {
        success: true,
        eventID: params[:event_id]
      }
    else
      UserEvent.find(params[:id]).destroy
      @event.destroy
      render json: {
        success: true,
        eventID: params[:event_id]
      }
    end
  end

  private

  def event_params
    params.permit(:name, :location, :description, :attend)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = JobCreator.create_jobs(params)
    fresh_when etag: @jobs
  end

  def show
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      @current_user.jobs << @job
      render json: {
        success: true,
        jobId: params[:job_id]}
    else
      render json: { success: false }
    end
  end

  def destroy
    @job = Job.find(params[:id])
    if @job.users.length > 1
      UserJob.find_by(job_id: params[:id]).destroy
      render json: {
        success: true,
        jobId: params[:job_id]
      }
    else
      UserJob.find_by(job_id: params[:id]).destroy
      @job.destroy
      render json: {
        success: true,
        jobId: params[:job_id] }
    end
  end

  private

  def job_params
    params.permit(:title, :company, :location, :description, :position, :date_posted, :apply)
  end
end

app/controllers/sessions_controller.rb
require 'google/api_client'

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def google_auth
    #session[:user_id] = User.last.id
    @user = User.find(session[:user_id])
    @user.add_omniauth_params(request.env["omniauth.auth"])
    redirect_to user_path(@user)

    # @auth = request.env["omniauth.auth"]
    # #Use the token from the data to request a list of calendars
    # @token = @auth["credentials"]["token"]
    # client = Google::APIClient.new
    # client.authorization.access_token = @token
    # service = client.discovered_api('calendar', 'v3')
    # @result = client.execute(
    #   :api_method => service.calendar_list.list,
    #   :parameters => {},
    #   :headers => {'Content-Type' => 'application/json'})
  end

  def create
    #@user = User.from_omniauth(request.env["omniauth.auth"])

    @user = User.find_by(username: params[:user][:username])

    # if login_url(params[:username], params[:password])
    #   redirect_back fallback_location: users_path
    #   @user = User.find_by(username: params[:user][:username])
    # else
    #   flash.now.alert = "Login failed."
    #   render action: :new
    # end
    #binding.pry

    if @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
    #What data comes back from OmniAuth?

      redirect_to user_path(@user)
    else
      # flash[:alert] = "Login Failed, bro"
      redirect_to root_path, alert: "Login failed, please remember your information, bro"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:current_org] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for joining TechMe, bro. Your account has be activated."
    else
      flash.now[:alert] = "There was an error with your registration. Please try again."
      render 'registrations/new'
    end
  end

  def show
    @job = Job.new
    @event = Event.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_application_wizard.html.erb
<!--Application Wizard-->
<section class="page-block" id="wizard">
  <div class="container">
    <div class="row page-header">
      <h2>Application wizard</h2>
      <span>Subtext for header</span>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="wizard">
          <div class="header">
            <h3>Application Wizard</h3>
            <div class="progress-bar group">
              <div class="overlay"></div>
              <div class="line"></div>
              <a class="step-link left current" href="#step01" data-toggle="tab"><span class="status"></span></a>
              <a class="step-link middle" href="#step02" data-toggle="tab"><span class="status"></span></a>
              <a class="step-link right" href="#step03" data-toggle="tab"><span class="status"></span></a>
            </div>
          </div>

          <form method="post" id="wizard-form" class="wizard-form body" role="form">

            <!--Step 1-->
            <div class="wizard-step fade in active" id="step01">
            <div class="tab-links-wrap">
              <div class="overlay"></div>
              <div class="row tab-links">
               <div class="tab-link active col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <a href="#contact" data-toggle="tab"><i class="fa fa-user"></i><span>Contact details</span></a>
                </div>
                <div class="tab-link col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <a href="#background" data-toggle="tab"><i class="fa fa-suitcase"></i><span>Background</span></a>
                </div>
                <div class="tab-link col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <a href="#id" data-toggle="tab"><i class="fa fa-check-circle-o"></i><span>ID Proof</span></a>
                </div>
                <div class="tab-link col-lg-3 col-md-3 col-sm-3 col-xs-3">
                  <a href="#agreement" data-toggle="tab"><i class="fa fa-file-text"></i><span>Agreement</span></a>
                </div>
              </div>
            </div>
              <div class="tabs">
                <div class="tab row fade in active" id="contact">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="name">Name (required)</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Enter your name" required>
                      </div>
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="email">Email (required)</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Enter your email" required>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="adress">Adress</label>
                        <input type="text" name="adress" class="form-control" id="adress" placeholder="Enter your adress">
                      </div>
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="phone">Phone (required numbers only)</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Enter your phone">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab row fade" id="background">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="education">Educational background</label>
                        <textarea class="form-control" name="education" id="education" rows="8" placeholder="Describe your educational background"></textarea>
                      </div>
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="profession">Professional background</label>
                        <textarea class="form-control" name="profession" id="profession" rows="8" placeholder="Describe your professional background"></textarea>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab row fade" id="id">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="security">Social security no (required numbers only)</label>
                        <input type="text" name="security" class="form-control" id="security" placeholder="Enter social security no" required>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="exp_date">ID expiry date</label>
                        <input type="text" name="exp_date" class="form-control" id="exp_date" placeholder="Enter ID expiry date">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab row fade" id="agreement">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="form-group">
                          <label for="agreem">Agreement no</label>
                          <input type="text" name="agreem" class="form-control" id="agreem" placeholder="Enter agreement no">
                        </div>
                        <div class="form-group">
                          <div class="checkbox custom">
                            <label>
                              <input class="icheckbox" name="terms" type="checkbox">I have read and agree to the terms of service
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                        <label for="education">Agreement</label>
                        <textarea class="form-control" name="agr_text" id="agr_text" rows="8" placeholder="Write agreement here"></textarea>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!--Step 2-->
            <div class="wizard-step fade" id="step02">
              <div class="tab-links-wrap">
                <div class="overlay"></div>
                <div class="row tab-links">
                  <div class="tab-link active col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <a href="#tab01" data-toggle="tab"><i class="fa fa-anchor"></i>Tab 01</a>
                  </div>
                  <div class="tab-link col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <a href="#tab02" data-toggle="tab"><i class="fa fa-anchor"></i>Tab 02</a>
                  </div>
                </div>
              </div>
              <div class="tabs">
                <div class="tab row fade in active" id="tab01">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="form-group col-lg-6 col-md-6 col-sm-6">
                        <label for="field01">Field 01</label>
                        <input type="text" name="field01" class="form-control" id="field01" placeholder="Placeholder">
                      </div>
                      <div class="form-group col-lg-6 col-md-6 col-sm-6">
                        <label for="field02">Field 02</label>
                        <input type="text" name="field02" class="form-control" id="field02" placeholder="Placeholder">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                        <label for="textarea01">Textarea (required)</label>
                        <textarea class="form-control" name="textarea01" id="textarea01" rows="8" placeholder="Placeholder" required></textarea>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab row fade" id="tab02">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="form-group">
                          <label for="field03">Field 03</label>
                          <input type="text" name="field03" class="form-control" id="field03" placeholder="Placeholder">
                        </div>
                        <div class="form-group">
                          <label for="field04">Field 04</label>
                          <input type="text" name="field04" class="form-control" id="field04" placeholder="Placeholder">
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                          <label for="textarea02">Textarea</label>
                          <textarea class="form-control" name="textarea02" id="textarea02" rows="8" placeholder="Placeholder"></textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!--Step 3-->
            <div class="wizard-step fade" id="step03">
              <div class="tab-links-wrap">
                <div class="overlay"></div>
                <div class="row tab-links">
                  <div class="tab-link active col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <a href="#tab03" data-toggle="tab"><i class="fa fa-anchor"></i>Tab 03</a>
                  </div>
                  <div class="tab-link col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <a href="#tab04" data-toggle="tab"><i class="fa fa-anchor"></i>Tab 04</a>
                  </div>
                </div>
              </div>
              <div class="tabs">
                <div class="tab row fade in active" id="tab03">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="form-group">
                          <label for="field05">Field 05</label>
                          <input type="text" name="field05" class="form-control" id="field05" placeholder="Placeholder">
                        </div>
                        <div class="form-group">
                          <label for="field06">Field 06</label>
                          <input type="text" name="field06" class="form-control" id="field06" placeholder="Placeholder">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab row fade" id="tab04">
                  <div class="col-lg-12">
                    <div class="row">
                      <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="form-group">
                          <label for="field07">Field 07</label>
                          <input type="text" name="field07" class="form-control" id="field07" placeholder="Placeholder">
                        </div>
                        <div class="form-group">
                          <label for="field08">Field 08</label>
                          <input type="text" name="field08" class="form-control" id="field08" placeholder="Placeholder">
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                          <label for="textarea03">Textarea03</label>
                          <textarea class="form-control" name="textarea03" id="textarea03" rows="8" placeholder="Placeholder"></textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="wizard-footer group">
              <div class="buttons">
                <a class="btn btn-primary prev-tab hidden" href="#">Back</a>
                <a class="btn btn-primary next-tab" href="#">Continue</a>
                <input class="btn btn-primary hidden" type="submit" id="submit-wizard" value="Submit form">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_charts.html.erb
<!--Charts-->
<section class="page-block less-space-bottom" id="charts">
  <div class="container">
    <div class="row page-header">
      <h2>Animated charts</h2>
      <span>Subtext for header</span>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 chart">
        <h3>Line Chart</h3>
        <canvas id="lineChart" width="550" height="320"></canvas>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 chart">
        <h3>Bar Chart</h3>
        <canvas id="barChart" width="550" height="320"></canvas>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 chart">
        <h3>Pie Chart</h3>
        <div class="group">
          <div class="pie-chart">
            <canvas id="pieChart" width="260" height="260"></canvas>
          </div>
          <div class="pie-chart-legend animated-legend">
            <div style="color:#ff6f69;" class="label"><span>20%</span>Item01</div>
            <div style="color:#e7e7ea;" class="label"><span>25%</span>Item02</div>
            <div style="color:#313447;" class="label"><span>40%</span>Item01</div>
            <div style="color:#ffad10;" class="label"><span>15%</span>Item02</div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 chart">
        <h3>Doughnut Chart</h3>
        <div class="group">
          <div class="pie-chart">
            <canvas id="doughnutChart" width="260" height="260"></canvas>
          </div>
          <div class="pie-chart-legend animated-legend">
            <div style="color:#ff6f69;" class="label"><span>20%</span>Item01</div>
            <div style="color:#e7e7ea;" class="label"><span>25%</span>Item02</div>
            <div style="color:#313447;" class="label"><span>40%</span>Item01</div>
            <div style="color:#ffad10;" class="label"><span>15%</span>Item02</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_contact_us.html.erb
<!--Contacts-->
<% cache do %>
<section class="page-block contacts" id="contacts">
  <div class="container">
    <div class="row page-header">
      <h2>Contacts</h2>
      <span>Hit us up, bro</span>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-4">
        <div class="row space-bottom">
          <div class="col-lg-9 col-md-9">
            <h3>What we do</h3>
          </div>
          <div class="col-lg-3 col-md-3">
            <%= image_tag "contacts/man.png", class:"img-center", alt:"About Us" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <p class="text-justify">We speak amazing latin: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-lg-offset-1">
        <div class="row space-bottom">
          <div class="col-lg-8 col-md-8">
            <h3>Adress</h3>
          </div>
          <div class="col-lg-4 col-md-4">
            <%= image_tag "contacts/map.png", class:"img-center", alt:"Adress" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <p>11 Broadway #260, New York, NY 10004</p>
          </div>
        </div>
        <div class="row space-bottom">
          <div class="col-lg-8 col-md-8">
            <h3>Contacts</h3>
          </div>
          <div class="col-lg-4 col-md-4">
            <%= image_tag "contacts/phone.png", class:"img-center", alt:"Contacts" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <p>+48 555 234 54 34<br/>+48 555 234 54 33<br/>info@email.com<br/>support@email.com</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-lg-offset-1">
        <div class="row space-bottom">
          <div class="col-lg-8 col-md-8">
            <h3>Contact us</h3>
          </div>
          <div class="col-lg-4 col-md-4">
            <%= image_tag "contacts/plan.png", class:"img-center", alt:"Adress" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <form method="post" class="feedback-form ajax-form" role="form">
              <div class="form-group">
                <label class="sr-only" for="name1">Name</label>
                <input type="text" class="form-control" name="name" id="name1" placeholder="Name">
              </div>
              <div class="form-group">
                <label class="sr-only" for="email1">Email</label>
                <input type="email" class="form-control" name="email" id="email1" placeholder="Email">
              </div>
              <div class="form-group">
                <label class="sr-only" for="message">Message</label>
                <textarea class="form-control" name="message" id="message" rows="5" placeholder="Message"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
              <!-- Validation Response -->
              <div class="response-holder"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/layouts/_features.html.erb
<% cache do %>

<div class="container">
  <div class="row page-header">
    <h2>Features</h2>
    <span>Subtext for header</span>
  </div>
  <div class="row features">
    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="feature-img"><%= image_tag "features/feature1.png", width:"124", height:"120", alt:"Editable colors" %></div>
      <h3>Editable colors</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo.</p>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="feature-img"><%= image_tag "features/feature2.png", width:"131", height:"131", alt:"All you need for start" %></div>
      <h3>All you need for start</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo.</p>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="feature-img"><%= image_tag "features/feature3.png", width:"72", height:"72", alt:"Clean code" %></div>
      <h3>Clean code</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo.</p>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<%= render 'sessions/nav_login' %>

<!--Header-->
<% cache do %>
<header class="stiky-header">
  <div class="container group">
    <% if @current_user %>
      <a class="logo" href="<%= user_path(@current_user) %>" data-method="get"><%= image_tag "TechMe-logo3.png", style: "height: 60px;", alt:"TechMe" %></a>
      <a class="logo-mobile" href="<%= user_path(@current_user) %>" data-method="get"><%= image_tag "TechMe-logo3.png", alt:"TechMe" %></a>
    <% else %>
      <a class="logo" href="<%= root_path %>" data-method="get"><%= image_tag "TechMe-logo3.png", style: "height: 60px;", alt:"TechMe" %></a>
      <a class="logo-mobile" href="<%= root_path %>" data-method="get"><%= image_tag "TechMe-logo3.png", alt:"TechMe" %></a>
    <% end %>
    <div class="navi-toggle group">
      <span class="dot"></span><span class="line"></span>
      <span class="dot"></span><span class="line"></span>
      <span class="dot"></span><span class="line"></span>
      <span class="dot"></span><span class="line"></span>
    </div>

    <% if @current_user %>
      <a class="btn btn-primary btn-login" href="<%= logout_path %>" data-method="delete"><i class="icon-user"></i>Logout</a>
    <% else %>
      <a class="btn btn-primary btn-login" href="#" data-toggle="modal" data-target="#loginModal"><i class="icon-user"></i>Login</a>
      <a href="<%= new_registration_path %>" class="btn btn-success btn-login" data-method="get"><i class="icon-user"></i>Sign Up</a>
    <% end %>
    <nav class="main-navi">
      <ul>
        <% if @current_user %>
          <li class="active"><a class="scroll-up" href="<%= user_path(@current_user) %>" data-method="get">Home</a></li>
          <li class="has-dropdown"><a href="<%= user_path(@current_user) %>" data-method="get">Features<i class="fa fa-caret-down"></i></a>
            <ul class="dropdown">
              <li><a class="scroll" href="<%= user_path(@current_user) %>#calendar">Calendar</a></li>
              <li><a class="scroll" href="<%= user_path(@current_user) %>#events">Events</a></li>
              <li><a class="scroll" href="<%= user_path(@current_user) %>#jobs">Jobs</a></li>
            </ul>
        <% else %>
          <li class="active"><a class="scroll-up" href="<%= root_path %>" data-method="get">Home</a></li>
          <li class="has-dropdown"><a href="<%= root_path %>" data-method="get">Features<i class="fa fa-caret-down"></i></a>
            <ul class="dropdown">
              <li><a class="scroll" href="<%= root_path %>#calendar">Calendar</a></li>
              <li><a class="scroll" href="<%= root_path %>#events">Events</a></li>
              <li><a class="scroll" href="<%= root_path %>#jobs">Jobs</a></li>
            </ul>
        <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>
<% end %>